import { Schema, model, type InferSchemaType, type Types } from 'mongoose';
import { PROPERTY_TYPES, USER_ROLES } from '../constants/enums';

const userSchema = new Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true, lowercase: true },
    passwordHash: { type: String, required: true },
    phoneNumber: { type: String },
    phoneCountryIso: { type: String },
    phoneCountryDialCode: { type: String },
    role: { type: String, enum: USER_ROLES, default: 'guest', required: true },
    hostOnboarding: {
      propertyName: { type: String },
      propertyType: { type: String, enum: PROPERTY_TYPES },
    },
    hostCompliance: {
      businessContact: {
        businessPhoneNumber: { type: String },
        businessPhoneCountryIso: { type: String },
        businessPhoneCountryDialCode: { type: String },
        trustedWhatsappNumber: { type: String },
        trustedWhatsappCountryIso: { type: String },
        trustedWhatsappCountryDialCode: { type: String },
        officeAddress: { type: String },
        officeLga: { type: String },
        officeState: { type: String },
        website: { type: String },
        completedAt: { type: Date },
      },
      manager: {
        managerName: { type: String },
        dateOfBirth: { type: Date },
        nationality: { type: String },
        ninNumber: { type: String },
        ninDocumentUrl: { type: String },
        managerHomeAddress: { type: String },
        proofOfAddressUrl: { type: String },
        completedAt: { type: Date },
      },
      bankAccount: {
        accountNumber: { type: String },
        bankCode: { type: String },
        bankName: { type: String },
        accountName: { type: String },
        verificationStatus: { type: String, default: 'pending_manual_review' },
        completedAt: { type: Date },
      },
      serviceAgreement: {
        accepted: { type: Boolean, default: false },
        acceptedAt: { type: Date },
        version: { type: String },
      },
      isBusinessActive: { type: Boolean, default: false },
      activatedAt: { type: Date },
    },
    guestOnboarding: {
      phoneNumber: { type: String },
      phoneCountryIso: { type: String },
      phoneCountryDialCode: { type: String },
      isWhatsappNumber: { type: Boolean, default: false },
      whatsappNumber: { type: String },
      whatsappCountryIso: { type: String },
      whatsappCountryDialCode: { type: String },
      ninNumber: { type: String },
      ninDocumentUrl: { type: String },
      verified: { type: Boolean, default: false },
      completedAt: { type: Date },
    },
    emailVerified: { type: Boolean, default: false },
    emailVerifiedAt: { type: Date, default: null },
    isSuspended: { type: Boolean, default: false, index: true },
    suspendedAt: { type: Date, default: null },
    hostVerified: { type: Boolean, default: false },
    bvn: { type: String },
    idDocumentUrl: { type: String },
    bankDetails: {
      accountNumber: { type: String },
      bankCode: { type: String },
      bankName: { type: String },
      accountName: { type: String },
      recipientCode: { type: String },
    },
    profileChangeRequests: [
      {
        section: {
          type: String,
          enum: ['host_manager', 'host_business_contact', 'host_property', 'guest_profile'],
          required: true,
        },
        status: {
          type: String,
          enum: ['pending', 'approved', 'rejected'],
          default: 'pending',
          required: true,
        },
        requestedByUserId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
        requestedAt: { type: Date, default: Date.now, required: true },
        reviewedAt: { type: Date, default: null },
        reviewedByAdminId: { type: Schema.Types.ObjectId, ref: 'User', default: null },
        note: { type: String, default: '' },
        oldValue: { type: Schema.Types.Mixed, default: {} },
        newValue: { type: Schema.Types.Mixed, default: {} },
      },
    ],
  },
  { timestamps: true },
);

export type UserDocument = InferSchemaType<typeof userSchema> & { _id: Types.ObjectId };
export const UserModel = model('User', userSchema);
